name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract tag name
      shell: bash
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      id: extract_tag
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./
        # Note: tags has to be all lower-case
        tags: |
          hectorcao84/checkbox:${{ steps.extract_tag.outputs.tag }}
          ghcr.io/petitfou/checkbox:${{ steps.extract_tag.outputs.tag }}
        #push: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
